### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by FireFlyForLife** [AndreyG/ifc-reader#17]
It would be good to have some unit tests to maintain the library, as you mentioned too.

The simple approach would be to upload a bunch of `.ifc` files for specific tests.

However, I'd argue it's also important to build those `.ifc`'s from source code. So you are verifying a platform instead of just the platform of the developer who uploaded that specific `.ifc` file. So I prefer this approach.

My issue is I am not aware of a reliable way to get the path to a `.ifc` file from a `.ixx` file. 
Eg Visual Studo Open Folder (so with Ninja as the build system) will follow relative subfolders to the .ifc file, and a .sln build will plonk everything in the intermediate directory.

Do you think this be abstracted in the MSVCEnvironment? we could have different defines identifying if we are running from CMake, Visual Studio, Ninja or MSBuild for example.

(Incidently this linking of an `.ixx` to it's `.ifc` file is something I need to solve for my own side project too.

**Comment by AndreyG** [comment]
Yep, basically the purpose of `MSVCEnvironment` is to abstract how to get path to needed `.ifc`.
I don't like idea to build `.ifc` on the fly, because it seems to be too tedious. IMO upload prebuilt `.ifc` with its source `.ixx` and short description how `.ifc` was built from the source should be enough. Description could contain compiler version and some important compiler options (i.e. `/std:{c++20/c++23/...}` and so on).
Moreover this description could be verified in test in some sense, because `.ifc` contains some [metadata](https://github.com/AndreyG/ifc-reader/blob/master/lib/core/include/ifc/FileHeader.h#L49) i.e. `Version`, `Architecture`, `LanguageVersion`, ...

**Comment by AndreyG** [comment]
I have added very very simple unit tests (CMake option `BUILD_IFC_READER_TESTS`). In particular I have added [test](https://github.com/AndreyG/ifc-reader/blob/master/tests/core/src/main.cpp#L67) for attributes reading functionality.

**Comment by AndreyG** [comment]
And [test](https://github.com/AndreyG/ifc-reader/blob/master/tests/msvc/src/main.cpp#L73) for multiple files.
